import json
from playwright.sync_api import sync_playwright

def inject_template_with_open_browser(instrument_id: str, template_payload_json_str: str) -> None:
    # 1. Parse the JSON string so we can pass it as a Python dictionary
    payload = json.loads(template_payload_json_str)

    with sync_playwright() as p:
        print("🤖 Launching browser...")
        browser = p.chromium.launch(headless=False)
        context = browser.new_context()
        page = context.new_page()

        print("🌐 Navigating to Reductus...")
        page.goto("https://reductus.nist.gov", wait_until="networkidle", timeout=120000)

        print("⏳ Waiting for the editor engine to initialize...")
        page.wait_for_function(
            "window.editor && typeof window.editor.load_template === 'function'",
            timeout=120000,
        )

        print("💉 Injecting template payload...")
        # 2. Pass multiple variables safely by packing them into a single dictionary
        page.evaluate(
            """async (args) => {
                if (!window.editor || typeof window.editor.load_template !== 'function') {
                    throw new Error("window.editor.load_template is not available");
                }
                // 3. Call the function with the exact argument order it expects
                return await window.editor.load_template(args.payload, 0, null, args.inst_id);
            }""",
            {"inst_id": instrument_id, "payload": payload},
        )

        print("✅ Injection complete! You can now use the browser.")
        print("🛑 The terminal will automatically exit when you close the browser tab.")
        
        # 4. Wait gracefully. The script will pause here until the user closes the window.
        page.wait_for_event("close", timeout=0)


# ==========================================
# Example Execution
# ==========================================
if __name__ == "__main__":
    # Simulate the raw JSON string generated by your AI
    sample_payload = json.dumps({
        "modules": [
            { "module": "ncnr.refl.super_load", "title": "Raw Data Source", "x": 100, "y": 150 },
            { "module": "ncnr.refl.abinitio_footprint", "title": "Footprint Config", "x": 400, "y": 150 }
        ],
        "wires": [
            { "source": [0, "output"], "target": [1, "data"] }
        ]
    })
    
    inject_template_with_open_browser("ncnr.refl", sample_payload)